name: CI4
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 */7 * *"
  # push:
  #   branches:
  #     - main

jobs:
  run4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone
        uses: actions/checkout@v4
        with:
          repository: ${{secrets.REPO_NAME}}
          token: ${{secrets.ACCESS_TOKEN}}
          path: ./work1

      # 安装 rclone
      - name: Install rclone
        run: |
          curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
          unzip rclone-current-linux-amd64.zip
          sudo mv rclone-*-linux-amd64/rclone /usr/bin/
          rm rclone-current-linux-amd64.zip
          rm -rf rclone-*-linux-amd64
          rclone version

      # 配置 rclone
      - name: Setup rclone config
        env:
          RCLONE_CONFIG_BASE64: ${{ secrets.RCLONE_CONFIG }}
        run: |
          echo "$RCLONE_CONFIG_BASE64" | base64 -d > ~/.config/rclone/rclone.conf
          chmod 600 ~/.config/rclone/rclone.conf

      - name: Run3
        run: |
          cd ./work1
          python info.py
          python main4.py
          du -sh *
          > ~/.config/rclone/rclone.conf

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: v${{ env.BTIME }}
      #     release_name: Release ${{ env.BUILDTIME }}
      #     draft: false  # 是否为草稿
      #     prerelease: false  # 是否为预发布

      # - name: Create and Upload Release
      #   id: upload_release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     release_name: Release ${{ env.BUILDTIME }}
      #     tag: v${{ env.BTIME }}
      #     file_glob: true
      #     overwrite: true
      #     file: ./code-archive/*

      # # 安装 rclone
      # - name: Install rclone
      #   run: |
      #     curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
      #     unzip rclone-current-linux-amd64.zip
      #     sudo mv rclone-*-linux-amd64/rclone /usr/bin/
      #     rm rclone-current-linux-amd64.zip
      #     rm -rf rclone-*-linux-amd64
      #     rclone version

      # # 配置 rclone
      # - name: Setup rclone config
      #   env:
      #     RCLONE_CONFIG_BASE64: ${{ secrets.RCLONE_CONFIG }}
      #   run: |
      #     echo "$RCLONE_CONFIG_BASE64" | base64 -d > ~/.config/rclone/rclone.conf
      #     chmod 600 ~/.config/rclone/rclone.conf

      # 上传文件到 OneDrive
      # - name: Upload files to OneDrive
      #   run: |
      #     rclone copy ./code-archive gh_bk:/backup_repos/${{ env.BTIME }}
      #     rclone copy main.py url.py gh_bk:/backup_repos/${{ env.BTIME }}
      #     rclone copy .github gh_bk:/backup_repos/${{ env.BTIME }}
      #     rm -rf ~/.config/rclone/rclone.conf